### ISSUE TITLE
About makefile 

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#121]
@pezy , First , Thank you for accepting and trying to write makefile ! 
But you should test makefile by executing "make all" in the ch**,or the root directory ! 
Makefile of the root directory is to execute makefile in the ch**. 

This is my fault ! I only want you to use makefile ,But I don't give the readme for it   !
Maybe I should write a simple todo to tell how to make and how to write a makefile !

**Comment by pezy** [comment]
Sorry, I don't agree to add makefile to `master` branch. You can see [my repo](https://github.com/pezy/Cpp-Primer), I added a branch which name is `gcc`.

And I just check the ch12, don't care about root directory, (cause you will do that, right? )

I certainly know the value of the makefile, and sometimes I use it in my work. I also use many other similar tools, like `cmake`. But I don't think we should add those things to our repo.

The reasons I have already said in #95 . And I think `alias` is enough.

We make all the exercise codes. :sob:  Do you really think this work makes any sense?

We learn c++ from this big book, rather than a variety of methods to use commonly tools.

thank you for contribution, and I also write the makefile to support you. :smile:

**Comment by mudongliang** [comment]
I think if every file structure is like ch01,ch02 and so on ,( One cpp file is for one aim!)
we don't need makefile ! But in the source code , I see the little complex dependency !
for example ,
factMain: factMain.o fact.o
	$(CC) $(CCFLAGS) $(LOCFLAGS) -o $@ factMain.o fact.o
ex7_41_TEST:ex7_41_TEST.o ex7_41.o
	$(CC) $(CCFLAGS) $(LOCFLAGS) -o $@ ex7_41_TEST.o ex7_41.o
ex7_26.o:ex7_26.cpp
	$(CC) $(CCFLAGS) $(LOCFLAGS) -o $@ -c $<
ex8_06 : ex8_06.o ../ch07/ex7_26.o
	$(CC) $(CCFLAGS) $(LOCFLAGS) -o $@ ex8_06.o ../ch07/ex7_26.o
ex8_07 : ex8_07.o ../ch07/ex7_26.o
	$(CC) $(CCFLAGS) $(LOCFLAGS) -o $@ ex8_07.o ../ch07/ex7_26.o
ex8_08 : ex8_08.o ../ch07/ex7_26.o
	$(CC) $(CCFLAGS) $(LOCFLAGS) -o $@ ex8_08.o ../ch07/ex7_26.o

This wastes much time to find this !!!
......

**Comment by pezy** [comment]
> little complex dependency

IMO, If you really read this book and code for exercise one by one, you will see the dependency is also a part of the content of knowledge.

> This wastes much time to find this

wastes much time? the running result is meaningless, but the codes maybe inspire some guys. The important thing is CODE, rather than the running result. If you care about the codes, I don't think it wastes time to read it.

As @Mooophy said in #108 .
> The problem is that this repo has been modified by around 20 people within over 10 months. As a result it's quite hard to keep every thing consistent..sorry for that..

and why ch01 ~ ch12 don't have any subfolder? I did it. And I suppose we should keep the consistent through the whole repo. Indeed, it wastes more time than copying the makefile from [source files of this book](http://www.informit.com/store/c-plus-plus-primer-9780321714114)

By the way, `VIM` or `shell` also useful and worth learning, we should write some README to teach the guys who want to only learn the c++?

IMO, the IDE can save more and more time to compile and run those codes.

**Comment by mudongliang** [comment]
IMO, I think maybe no one will do the exercise one by one .
people can read and research source code in the book .When they understand the program , they may not see the code ,and only want to check the result ! 
Only the difficult ones , they will check the code and do an experiment on it !
If we provide make for reader , they can execute by "make all" to  compile all the source code ! 
I know you understand makefile , so you will know a feature of make : 
        if a target is updated , make will recompile it ! 
        else make will do nothing !
This helps to see the result of modified code by reader !
Moreover ,  I don't look down upon the IDE , but I think we should have the capability to do any programming  without IDE!

**Comment by pezy** [comment]
> people can read and research source code in the book .When they understand the program , they may not see the code ,and only want to check the result !
> Only the difficult ones , they will check the code and do an experiment on it !

Yes, I don't realize this way, sorry for it.

> if a target is updated , make will recompile it !

Actually, this function is very useful to help us to improve.

`Makefile` is necessary, thank you for your reminder. 

(I think we can close this issue now, right?)

**Comment by mudongliang** [comment]
OK!
