### ISSUE TITLE
ch09/ex9_32.cpp

### ISSUE THREAD

**Issue by dom68** [Mooophy/Cpp-Primer#125]
ch09/ex9_32.cpp

FYI, I believe in Update ex9_32.cpp
iter = vi.insert(iter, *iter++); statement
 will insert *iter into the container after incrementing the pointer, not before the pre-incremented iter pointer.
tested it with the statement iter = vi.insert(iter, - *iter++); so I could discriminate.  The corrected statement should be instead iter = vi.insert(iter, *iter);  ++iter;  
this statement may also refers to the section of the book  4.1.3 Order of Evaluation, Precedence, and Associativity where  incrementing the second argiment will affect the first argument in the insert function

thanks,
dom68

**Comment by Mooophy** [comment]
Hi~ @dom68 
Thx for issue reporting.
The current answer in this repo indeed has problem. But it isn't like what you said. First of all, the following statement is illegal :
```cpp
iter = vi.insert(iter, *iter++); 
```
Because as said in Standard [5.2.2]
>The order of evaluation of arguments is unspecified.

Check this [post] (http://stackoverflow.com/questions/2934904/order-of-evaluation-in-c-function-parameters) for more discussion. 
As a result, after entering function `insert`, `iter` could be its original value or original value + 1 or even anything else, depending on how compiler has been implemented.

As for your version :
```cpp
iter = vi.insert(iter, *iter); 
++iter;
```

I tested it using the code from CP5, as this:
```cpp
#include <iostream>
#include <vector>
using namespace std;
int main()
{
    vector<int> vi = {0,1,2,3,4,5,6,7,8,9};
    auto iter = vi.begin();
    while (iter != vi.end())
    {
        if (*iter % 2)
        {
            iter = vi.insert(iter, *iter);
            ++iter;
        }
        else
        {
            iter = vi.erase(iter);
        }
    }
    for(auto i : vi)
        cout << i << " ";
    return 0;
}
```
I believe it's legal, but it led to a infinite loop. Please run it.

**Comment by dom68** [comment]
MooophyCpp-Primer
Thanks for you input.
dom68

Date: Sat, 10 Jan 2015 19:25:29 -0800

**Comment by IceFox99** [comment]
```cpp
```
