### ISSUE TITLE
ex9_31_2.cpp 

### ISSUE THREAD

**Issue by xiaodi528** [Mooophy/Cpp-Primer#224]
prev = vi.before_begin();

prev在循环里没有定义, 为什么程序能运行成功, 我觉得迭代器失效了啊.

**Comment by Mooophy** [comment]
```cpp
int main()
{
    forward_list<int> vi = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    auto iter = vi.begin(), prev = vi.before_begin();
//~~^^^^~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^ prev is defined with a type deduced by auto. 
    while (iter != vi.end()) {
        if (*iter % 2) {
            iter = vi.insert_after(prev, *iter);
            advance(iter, 2);
            advance(prev, 2);
        }
        else
            iter = vi.erase_after(prev);
    }

    for (auto i : vi)
        cout << i << " ";
    return 0;
}
```

**Comment by Mooophy** [comment]
For `std::forward_list`'s iterator invalidation rule:
>all iterators and references unaffected (applies to insert_after) [23.3.4.5/1]

Check [this post on SO](http://stackoverflow.com/questions/6438086/iterator-invalidation-rules) for detail.

**Comment by xiaodi528** [comment]
got it, thanks.

**Comment by xiaodi528** [comment]
got it, thanks!

**Comment by Mooophy** [comment]
As a suggestion, please try to digest containers by looking at underlying data structures. For example, `std::forward_list` is essentially singly linked list. That's why insertion operations invalidate no iterator. So does `std::list`, which is essentially doubly linked list.

As for `std::vector`, it's a dynamic array. Insertion operation on it may lead to reallocations. When such thing happens, all iterators and references are invalidated.
