### ISSUE TITLE
ex10_33.cpp Question

### ISSUE THREAD

**Issue by xiaodi528** [Mooophy/Cpp-Primer#232]
```cpp
for_each(is, iss, [&os,&oss](const int i){i%2 == 0 ? *os = i : *oss = i;} );  
```
is correct. I don't understand how an integer "i" could works here.. In my opinion, "i" should be istream_iterator<int>
```cpp
for_each(is, iss, [&os,&oss](istream_iterator<int> i){*i%2 == 0 ? *os = *is : *oss = *is;} );
```
why can't I use this method above?

**Comment by pezy** [comment]
Please see [std::for_each](http://en.cppreference.com/w/cpp/algorithm/for_each).

> The type `Type` must be such that an object of type `InputIt` can **be dereferenced** and then implicitly converted to `Type`.

​

**Comment by xiaodi528** [comment]
thanks.

**Comment by Mooophy** [comment]
@xiaodi528 Good question!

While @pezy has answered correctly this question in terms of C++ syntax and semantics , I'd like to look at it at a broader point of view. Actually, probably in any programming language that supports such syntax sugar,   `foreach` semantics  traverses **items** in a collection, **rather than their iterators**.   We can use several examples from other mainstream languages to justify this argument:

C#
```csharp
//ordinary c#
foreach (int x in myArray) { Console.WriteLine(x); }

//C# Linq
myArray.ToList().ForEach(x => Console.WriteLine(x));
```

Ruby
```ruby
set.each do |item|
  # do something to item
end
```

Swift
```swift
for i in 0..<10 {
    // 0..<10 constructs a half-open range, so the loop body
    // is repeated for i = 0, i = 1, …, i = 9.
}
 
for i in 0...10 {
    // 0...10 constructs a closed range, so the loop body
    // is repeated for i = 0, i = 1, …, i = 9, i = 10.
}
```
Reference : [Foreach_loop on wiki](http://en.wikipedia.org/wiki/Foreach_loop)

**Comment by Mooophy** [comment]
Specifically in C++,  `for range` and `std::for_each` are actually implemented with iterators, but we can not use iterators explicitly as shown in your code above.

Hope it helps.

**Comment by xiaodi528** [comment]
so can I say that for each iteration from is to iss, it's automatically dereferenced to int?

**Comment by Mooophy** [comment]
@xiaodi528 
>so can I say that for each iteration from is to iss, it's automatically dereferenced to int?

Exactly. :+1:

**Comment by xiaodi528** [comment]
thank you!!

**Comment by Mooophy** [comment]
@xiaodi528 
No worries.
Don't forget to close this issue when no more discussion is needed.
