### ISSUE TITLE
vector<string>::size_type using in map<>

### ISSUE THREAD

**Issue by xiaodi528** [Mooophy/Cpp-Primer#245]
using line_nm = vector<string>::size_type;
    map<string, set<line_nm>> word;

    map<string, set<vector<int>>> word;

I don't know what's the difference between these two. I was using the second one, then I got an error when I tried to insert numbers into word.

    word[str2].insert(line.size()-1);

**Comment by pezy** [comment]
@xiaodi528  Hi~

- The type of the first one is `vector<string>::size_type`. It's almost a size(number, such as 4, 5...etc).
- The second is `vector<int>`. It mean a `vector` **container**.(like a list, such as [1,2,3,4,5]...)

Back to your code.
`line.size()-1` is a size(number), rather than a container. 
Thus, you should use the first one.

**Comment by xiaodi528** [comment]
I see, but how to modify my code if I want to use the second one?

**Comment by pezy** [comment]
I'm not sure your intention, but you can try this:
```cpp
word[str2].emplace(1, line.size()-1);
```

**Comment by xiaodi528** [comment]
thanks!
