### ISSUE TITLE
Ex 12.26

### ISSUE THREAD

**Issue by xiaodi528** [Mooophy/Cpp-Primer#308]
void input_reverse_output_string(int n)
    {
        std::allocator<std::string> alloc;
        auto const p = alloc.allocate(n);
        std::string s;
        auto q = p;
        while (std::cin >> s && q != p + n)
            alloc.construct(q++, s);
    
        while (q != p)
        {
            std::cout << *--q << " ";
            alloc.destroy(q);
        }
        alloc.deallocate(p, n);
    }

    int main()
    {
        input_reverse_output_string(5);
    }

CPP (English version) on page 482, comments of `auto q = p` says **q will point to one past the last constructed element.** Does that means q is pointing to one past of p+n? If so, then `q != p + n` makes no sense. I think q is pointing to the same address of p does. I tried debug and I found that p and q shares same address.

**Comment by opensourceDA** [comment]
when u write 

    auto const p = alloc.allocate(n); // s0

p points the first of n blocks of memory allocated. Since here no element has been constructed, `p` is pointing to the first non-constructed element, that is, one past the first constructed element. :P i don't know if u get this. :D 
Then, when u write `auto q = p` , `q` and `p` point to the same address.

The program on pg 482 goes like this:

    auto q = p;                      //s1
    alloc.construct(q++);      // s2

So, here `q` and `p` are initially same. But when `s2` executes, the block of memory being pointed by `q` is constructed to be and empty string (Since here we did not give any second argument to `construct memeber` of the string `allocator alloc` the default constructor will be used) . But we also increment `q` in this call to construct. So, now `q` points to the next block of memory that was allocated by alloc in `s0` (scroll up, see the first statement). This memory currently pointed by `q` is unconstructed. Therefore the comment by the author is legit. `q` points to one past the last constructed element.

**Comment by xiaodi528** [comment]
Thank you! Now I understand what does "last" means. I thought "last" means q points to the last element that s1 allocated, which is p+n.
